version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./rag_store:/app/rag_store
    env_file:
      - .env
    restart: always
    command: gunicorn --bind 0.0.0.0:5000 --workers 4 run:app
