services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
    image: rag-bi-platform:latest
    container_name: rag-bi-platform
    ports:
      - "8080:5000"
    volumes:
      - ./rag_store:/app/rag_store
      - rag_data:/app/instance
    env_file:
      - .env
    restart: always
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - GUNICORN_WORKERS=2
      - GUNICORN_THREADS=4
      - GUNICORN_TIMEOUT=120
      - DATABASE_URL=sqlite:////app/instance/app.db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 512M
    logging:
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  rag_data:
    driver: local
